python ./examples/run_semeval.py \
--model_type roberta \
--task_name task4a \
--model_name_or_path roberta-large \
--do_train \
--do_eval \
--do_lower_case \
--data_dir /mnt/minerva1/nlp/projects/counterfactual/semeval/4/data/ \
--learning_rate 1e-5 \
--eval_all_checkpoints \
--num_train_epochs 35  \
--max_seq_length 210 \
--output_dir models_bert/roberta_4a \
--per_gpu_eval_batch_size=4 \
--per_gpu_train_batch_size=4 \
--gradient_accumulation_steps 12 \
--overwrite_output
