python ./examples/run_semeval.py \
--model_type roberta \
--task_name task4a \
--model_name_or_path roberta-large \
--do_eval \
--do_lower_case \
--data_dir /mnt/minerva1/nlp/projects/counterfactual/semeval/4/data/new \
--learning_rate 5e-6 \
--num_train_epochs 10 \
--max_seq_length 190 \
--output_dir models_bert/roberta4a_new_dev \
--per_gpu_eval_batch_size=6 \
--per_gpu_train_batch_size=6 \
--gradient_accumulation_steps 10 \
--seed 5432 \
--overwrite_output \
--eval_all_checkpoints --do_train \
