"""Creates a dataset that can be scored using model for task B.
Takes four arguments: first a csv file with 2 columns, id and statement,
and three files with task C system outputs (newline separated explanations generated by the model)."""
import sys,csv
with open(sys.argv[1]) as input_f,  open(sys.argv[2]) as f1,  open(sys.argv[3]) as f2, open(sys.argv[4]) as f3:
    print("id,FalseSent,OptionA,OptionB,OptionC")
    writer = csv.writer(sys.stdout)
    reader = csv.reader(input_f)
    for i,(row,line1,line2,line3) in enumerate(zip(reader,f1,f2,f3)):
        if i==0:
            continue
       # print([row[0],row[1],line1,line2,line3])
        writer.writerow([row[0],row[1],line1.strip(),line2.strip(),line3.strip()])
        
        

